version: "3"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      FLASK_APP: app.py
      FLASK_ENV: development

  watch:
    image: ivandotv/docker-watch
    volumes:
      - .:/app
    command: "python app.py"
    depends_on:
      - web
