# Generated by Django 3.2.12 on 2024-04-21 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TournamentProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_id', models.CharField(max_length=1)),
                ('player_1', models.CharField(max_length=20, null=True)),
                ('player_2', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TournamentTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, null=True)),
                ('number', models.CharField(max_length=1)),
                ('status', models.CharField(max_length=1)),
            ],
        ),
    ]
