# Generated by Django 5.0.3 on 2024-03-11 08:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_user_bio_user_name_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.CharField(default='../../static/assets/img/profile.png', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='field_color',
            field=models.CharField(default='blue', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='pong_history',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.ponggame'),
        ),
        migrations.AddField(
            model_name='user',
            name='ttt_history',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.tttgame'),
        ),
    ]
