# Generated by Django 5.0.3 on 2024-03-11 09:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_user_avatar_user_field_color_user_pong_history_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='pong_history',
        ),
        migrations.RemoveField(
            model_name='user',
            name='ttt_history',
        ),
        migrations.AddField(
            model_name='ponggame',
            name='name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tttgame',
            name='name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
