version: "3"

#networks:
#  transcendence:
#    name: transcendence
#    driver: bridge
services:
  db:
    image: postgres
    restart: on-failure
    volumes:
      - ./data/db:/var/lib/postgresql/data
    env_file:
      - ./env/postgres.env
    ports:
      - "5432:5432"
      
  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: on-failure
    env_file:
      - ./env/pgadmin.env
    ports:
      - "5050:80"
      
  web:
    build: .
    command: bash -c "
       chmod -R 777 ./data/
       && python3 manage.py runserver 0.0.0.0:8000
      "
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db